// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCODa27oum0jOcb7bnMDpqn0CH7QrW0dY',
    appId: '1:66276080627:web:24604d3a7614391f5ab086',
    messagingSenderId: '66276080627',
    projectId: 'beermate2',
    authDomain: 'beermate2.firebaseapp.com',
    storageBucket: 'beermate2.appspot.com',
    measurementId: 'G-9VN5EECLZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSNxKjDPNuTkLuRFBCFjUKhwA75GS5mwI',
    appId: '1:66276080627:android:e10a3d1330f9ec9e5ab086',
    messagingSenderId: '66276080627',
    projectId: 'beermate2',
    storageBucket: 'beermate2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8Y64lcz2z-suw690RvCmFyaj5-vLzc2c',
    appId: '1:66276080627:ios:557b6848f1673a3a5ab086',
    messagingSenderId: '66276080627',
    projectId: 'beermate2',
    storageBucket: 'beermate2.appspot.com',
    iosBundleId: 'com.example.beermate2',
  );
}
